baseURL = 'https://paroidea.github.io/tangut-story'
languageCode = 'zh-cn'
title = '西夏文字的故事'
theme = 'hugo-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
