flowchart TB
    eye["<span class=tangut>𗑉</span> <br/> 目、眼睛"] ~~~ a["<span class=tangut>𗄯</span> <br/> (a) 明显"] --> eye
    a --> c["<span class=tangut>𗮀</span> <br/> (c) 聪明，聪慧的“聪”"]
    c --> f["<span class=tangut>𗥨</span> <br/> (f) 聪慧的“慧”"]
    c --> d["<span class=tangut>𗋡</span> <br/> (d) 琉璃"]
    c --> e["<span class=tangut>𗲈</span> <br/> (e) 璃，玉璧"]
    eye ~~~ b["<span class=tangut>𘡊</span> <br/> (b)"] --> eye
    d --> de["<span class=tangut>𗋡𗲈</span> <br/> 琉璃"]
    e --> de