flowchart TB
    blood["<span class=tangut>𗊴</span> <br/> 血"]
    blood --> feeling["<span class=tangut>𘋤</span> <br/> 情"]
    blood --> blood_line["<span class=tangut>𘙞</span> <br/> 血脉"]
    blood --> blood_block["<span class=tangut>𗽫</span> <br/> 血块"]
    blood --> nong["<span class=tangut>𘒓</span> <br/> 脓"]
    feeling --> have_feeling["<span class=tangut>𘋤𗋐</span> <br/> 有情→众生"]
    feeling ---> feeling2["<span class=tangut>𘋤→𘋢𗥤</span> <br/> 菩萨 <br/>极少数字形在后代<br/>发生变化的例子之一"]