flowchart TB
    tounge["<span class=tangut>𗢯</span> <br/> 舌头"] --> delicious["<span class=tangut>𗠼</span> <br/> 美味"]
    tounge --> sweet["<span class=tangut>𗗘</span> <br/> 甜"]
    tounge --> slight["<span class=tangut>𗉼</span> <br/> 淡味"]
    tounge --> sour["<span class=tangut>𗤰/𗤰𗕄</span> <br/> 酸味 / 醋"]
    sweet --> sweet2["<span class=tangut>𗋔</span> <br/> 甜味"]
    sweet2 --> honey["<span class=tangut>𗋮/𗾡𗋮</span> <br/> 蜜 / 蜜蜂"]
    sour --> koji["<span class=tangut>𘌍</span> <br/> 麹、麯、曲"]
    koji ~~~ make_sour
    sour --> make_sour["<span class=tangut>𗒴</span> <br/> 酿造醋"]