flowchart TB
    a["<span class=tangut>𗯞</span> <br/> 鸣"]
    b["<span class=tangut>𗤪</span> <br/> 鸣"]
    c["<span class=tangut>𗊟</span> <br/> 响"]
    d["<span class=tangut>𗒳</span> <br/> 铎"]
    e["<span class=tangut>𘖱</span> <br/> 铃"]
    
    a --> b
    a --> c
    c --> d
    c --> e