flowchart TB
    g["<span class=tangut>𗨚</span> <br/> (g) 眼、眼珠"] --> j["<span class=tangut>𘝮</span> <br/> (j) 哭泣"]
    g --> i["<span class=tangut>𗔙</span> <br/> (i) 审查"]
    g --> gh["<span class=tangut>𘝯</span> <br/> 看"] --> h["<span class=tangut>𘝯𗸸</span> <br/> (h) 观察"]
    g --> gk["<span class=tangut>𘝳</span> <br/> 沉默"] --> k["<span class=tangut>𘝳𗥤</span> <br/> (k) 玄通"]
    gk --> l["<span class=tangut>𘝳𗣌</span> <br/> (l) 默然"]