flowchart TB
    a["<span class=tangut>𗰞</span> <br/> 黑"]
    b["<span class=tangut>𘊘</span> <br/> 蝌蚪"]
    c["<span class=tangut>𗪬</span> <br/> 夜"]
    d["<span class=tangut>𗕈</span> <br/> 水泥"]
    e["<span class=tangut>𗌌</span> <br/> 黑水"]
    f["<span class=tangut>𗓰</span> <br/> 深"]
    g["<span class=tangut>𗽼</span> <br/> 坑"]
    
    a --> b
    a --> c
    a --> d
    a --> e
    a --> f
    f --> g
