flowchart TD
    base[<span class="tangut">𗥦</span> <br/> 头] --> a["<span class="tangut">𗪟</span> <br/> (a) 起始"]
    a --> b["<span class="tangut">𗪘</span> <br/> (b) 先前"]
    a --> c["<span class="tangut">𗪭𗂣</span> <br/> (c) 前年"]
    a --> d["<span class="tangut">𗨋𗬥</span> <br/> (d) 大后天"]
    base --> h["<span class="tangut">𘅒</span> <br/> (h) 额头"]
    h ~~~ g["<span class="tangut">𘅞</span> <br/> (g) 脸₂"] --> h
    g --> i["<span class="tangut">𘅝</span> <br/> (i) 庆祝"]
    base --> f["<span class="tangut">𗣿</span> <br/> (f) 脸₁"]
    base --> e["<span class="tangut">𗪢</span> <br/> (e) 发髻"]
