flowchart TB
    e["<span class=tangut>𘠢</span> <br/> (e)"] --> f
    a --> f["<span class=tangut>𘚥</span> <br/> (f) 吕"]
    a --> d["<span class=tangut>𗠨</span> <br/> (d) 涎，口水"]
    mouth["<span class=tangut>𗢸</span> <br/> 口"] --> a["<span class=tangut>𗠉</span> <br/> (a) 唇"]
    mouth --> c["<span class=tangut>𗠃</span> <br/> (c) 唾"]
    mouth --> b["<span class=tangut>𗉿</span> <br/> (b) 唾液"]
    g["<span class=tangut>𗊇</span> <br/> (g) 枯竭"] --> h["<span class=tangut>𗠵</span> <br/> (h) 渴"]
    mouth --> mouth_side["<span class=tangut>𘡯</span> <br/> 口偏"] --> h
    j["<span class=tangut>𘨈</span> <br/> (j)"] --> i["<span class=tangut>𗠰</span> <br/> (i) 喝"]
    mouth_side --> i
    k["<span class=tangut>𗠰</span> <br/> (k) "] --> kl["<span class=tangut>𗠰𗶡</span> <br/> 醍醐 "]
    l["<span class=tangut>𗶡</span> <br/> (l) "] --> kl
    i <--> k