flowchart TB
    j["<span class=tangut>𗴵</span> <br/> (j) 头"] --> p["<span class=tangut>𗵡</span> <br/> (p) 戴上笠"]
    p ~~~ human["<span class=tangut>𘓐</span> <br/> 人"] --> p
    human --> q["<span class=tangut>𘓢</span> <br/> (q) 骑马"]
    j --> k["<span class=tangut>𗴹</span> <br/> (k) 脑"]
    l["<span class=tangut>𗵣</span> <br/> (l) 顶"] --> n["<span class=tangut>𗴸</span> <br/> (n) 顶上的毛发"]
    j --> l
    j ~~~ m
    m["<span class=tangut>𗁼</span> <br/> (m) 兑、金<br/>（原书标注为：元）"] --> l
    o["<span class=tangut>𗐄</span> <br/> (o) 毛发"] --> n